In [1]:
import polars as pl
from bert_score import BERTScorer
from tqdm.notebook import tqdm
from itertools import combinations

import numpy as np

In [2]:
df = pl.read_csv("full_corpus.csv")
df.shape

(388217, 199)

In [3]:
df.head()

shape: (5, 199)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ argument  ┆ argument_ ┆ prompt_id ┆ raw_seque ┆ … ┆ political ┆ ID_questi ┆ topic     ┆ conditio │
│ ---       ┆ id        ┆ ---       ┆ nce_lengt ┆   ┆ _spectrum ┆ on        ┆ ---       ┆ n        │
│ str       ┆ ---       ┆ str       ┆ h         ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ str       ┆           ┆ ---       ┆   ┆ str       ┆ i64       ┆           ┆ str      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Die Begre ┆ 2025-07-1 ┆ de_0      ┆ -0.783945 ┆ … ┆ null      ┆ 32216     ┆ Welfare   ┆ SD       │
│ nzung der ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆ state &   ┆          │
│ Rente auf ┆ 0.4959171 ┆           ┆           ┆   ┆           ┆           ┆ family    ┆          │
│ 1…        ┆ 36Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Die Begre ┆ 2025-07-1 ┆ de_0      ┆ -0.699438 ┆ … ┆ null      ┆ 32216     ┆ Welfare   ┆ SD       │
│ nzung der ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆ state &   ┆          │
│ Rente für ┆ 1.8350587 ┆           ┆           ┆   ┆           ┆           ┆ family    ┆          │
│ E…        ┆ 34Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Die Begre ┆ 2025-07-1 ┆ de_0      ┆ -0.495087 ┆ … ┆ null      ┆ 32216     ┆ Welfare   ┆ SD       │
│ nzung der ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆ state &   ┆          │
│ Rente auf ┆ 3.5557549 ┆           ┆           ┆   ┆           ┆           ┆ family    ┆          │
│ 1…        ┆ 15Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Die Begre ┆ 2025-07-1 ┆ de_1      ┆ -0.750142 ┆ … ┆ null      ┆ 32216     ┆ Welfare   ┆ SD       │
│ nzung der ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆ state &   ┆          │
│ Rentenhöh ┆ 4.9513965 ┆           ┆           ┆   ┆           ┆           ┆ family    ┆          │
│ e …       ┆ 43Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Ich       ┆ 2025-07-1 ┆ de_1      ┆ -0.756288 ┆ … ┆ null      ┆ 32216     ┆ Welfare   ┆ SD       │
│ denke,    ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆ state &   ┆          │
│ die Begre ┆ 6.1802421 ┆           ┆           ┆   ┆           ┆           ┆ family    ┆          │
│ nzung der ┆ 53Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
df["model"].unique()

shape: (5,)
Series: 'model' [str]
[
	"llama_4_scout"
	"occiglot-7b-eu5-instruct"
	"llama_3.1-8b-instruct"
	"gpt-4.1-mini"
	"Human"
]

In [9]:
# German

res = {
    "model": [],
    "prompt_id": [],
    "precision": [],
    "recall": [],
    "f1": []
}

scorer = BERTScorer(lang="de")
unique_combos = df.filter(pl.col("language")=="de", pl.col("model")!="Human").select("model", "prompt_id").unique()

for row in tqdm(unique_combos.iter_rows(), total=unique_combos.height):
    model, prompt_id = row

    sentences = df.filter(
        (pl.col("model") == model) & (pl.col("prompt_id") == prompt_id)
    )["argument"].to_list()

    pairs = list(combinations(sentences, 2))
    if not pairs:
        continue

    cands, refs = zip(*pairs)
    P, R, F1 = scorer.score(list(cands), list(refs))

    res["model"].append(model)
    res["prompt_id"].append(prompt_id)
    res["precision"].append(P.mean().item())
    res["recall"].append(R.mean().item())
    res["f1"].append(F1.mean().item())

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  0%|          | 0/60634 [00:00<?, ?it/s]

Warning: Empty reference sentence detected; setting raw BERTScores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.

In [11]:
res_df = pl.from_dict(res)

In [13]:
res_df.describe()

shape: (9, 6)
┌────────────┬──────────────────────────┬───────────┬───────────┬──────────┬──────────┐
│ statistic  ┆ model                    ┆ prompt_id ┆ precision ┆ recall   ┆ f1       │
│ ---        ┆ ---                      ┆ ---       ┆ ---       ┆ ---      ┆ ---      │
│ str        ┆ str                      ┆ str       ┆ f64       ┆ f64      ┆ f64      │
╞════════════╪══════════════════════════╪═══════════╪═══════════╪══════════╪══════════╡
│ count      ┆ 59123                    ┆ 59123     ┆ 59123.0   ┆ 59123.0  ┆ 59123.0  │
│ null_count ┆ 0                        ┆ 0         ┆ 0.0       ┆ 0.0      ┆ 0.0      │
│ mean       ┆ null                     ┆ null      ┆ 0.74368   ┆ 0.743742 ┆ 0.743091 │
│ std        ┆ null                     ┆ null      ┆ 0.079154  ┆ 0.079053 ┆ 0.078324 │
│ min        ┆ gpt-4.1-mini             ┆ de_0      ┆ 0.0       ┆ 0.0      ┆ 0.0      │
│ 25%        ┆ null                     ┆ null      ┆ 0.688769  ┆ 0.688484 ┆ 0.68675  │
│ 50%        ┆ null                     ┆ null      ┆ 0.753565  ┆ 0.75374  ┆ 0.753395 │
│ 75%        ┆ null                     ┆ null      ┆ 0.796441  ┆ 0.796546 ┆ 0.795657 │
│ max        ┆ occiglot-7b-eu5-instruct ┆ de_9999   ┆ 1.0       ┆ 1.0      ┆ 1.0      │
└────────────┴──────────────────────────┴───────────┴───────────┴──────────┴──────────┘

In [14]:
res_df.write_csv("bert_score_de.csv")

In [24]:
# Italian

res = {
    "model": [],
    "prompt_id": [],
    "precision": [],
    "recall": [],
    "f1": []
}

scorer = BERTScorer(lang="it")
unique_combos = df.filter(pl.col("language")=="it", pl.col("model")!="Human").select("model", "prompt_id").unique()

skipped = 0

for row in tqdm(unique_combos.iter_rows(), total=unique_combos.height):
    model, prompt_id = row

    sentences = df.filter(
        (pl.col("model") == model), (pl.col("prompt_id") == prompt_id),
    )["argument"].to_list()

    pairs = list(combinations(sentences, 2))
    if not pairs:
        continue

    try:
        cands, refs = zip(*pairs)
        P, R, F1 = scorer.score(list(cands), list(refs))
    
        res["model"].append(model)
        res["prompt_id"].append(prompt_id)
        res["precision"].append(P.mean().item())
        res["recall"].append(R.mean().item())
        res["f1"].append(F1.mean().item())
    except AttributeError:
        print(f"Attribute error in row {row}")
        skipped += 1

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  0%|          | 0/21537 [00:00<?, ?it/s]

Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1533')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2272')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3205')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1085')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2090')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1044')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3585')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3996')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5268')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1151')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1429')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1203')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2045')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1784')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5138')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5391')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2540')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5033')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1525')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2523')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3120')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3137')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5034')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4620')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4102')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_256')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3919')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4807')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2952')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1559')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4764')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2186')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1456')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3730')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1319')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_804')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5371')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3649')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1920')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1822')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1482')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1919')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1917')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3786')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5007')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4446')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2225')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1498')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2018')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1524')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1515')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4704')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4919')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_752')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2403')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1877')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4341')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4885')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4767')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4185')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3224')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2968')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3849')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1806')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2249')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2047')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2050')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4773')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4065')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4750')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1580')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1921')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1486')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_815')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2070')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2149')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1153')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_425')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3901')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4187')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4346')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4219')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4340')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3543')

Warning: Empty candidate sentence detected; setting raw BERTscores to 0.

Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4387')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4214')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1191')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3087')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4763')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2779')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3854')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1922')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2227')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3850')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1086')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5327')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2486')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3760')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5372')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3616')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4734')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4795')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2074')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5143')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4218')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5397')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4262')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1394')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1150')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1214')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4505')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4101')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1763')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4774')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5166')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1639')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1026')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4705')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1644')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2542')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5242')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1643')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5035')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2928')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1713')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4796')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1790')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4379')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3140')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1638')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4493')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1199')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1049')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1685')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2268')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4626')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5038')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4100')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4622')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1142')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4945')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4499')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1523')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1988')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4525')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1487')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1188')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3433')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1401')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1684')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1562')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2270')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4342')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3211')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4649')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4706')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4436')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1635')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3790')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4129')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4915')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4580')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_685')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1517')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5142')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4024')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1317')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1484')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1267')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3778')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1791')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1115')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2146')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3908')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3787')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1485')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4775')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2568')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2474')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3815')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4433')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1899')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3897')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4766')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4390')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5060')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3468')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2002')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3659')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3476')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2234')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2439')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1428')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3812')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3845')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1662')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3789')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1200')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5272')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1398')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5337')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2043')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_183')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1782')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1392')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3576')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3071')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1248')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2525')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5318')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4868')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_820')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2391')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4135')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1765')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4192')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2768')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2044')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1554')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1145')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1600')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1714')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4435')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_812')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2294')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1906')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2564')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4354')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_809')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3903')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2522')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2172')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4018')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1946')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1147')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1916')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4097')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3424')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4753')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5032')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4221')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1497')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5271')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4226')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1734')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3891')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_180')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4201')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1204')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1387')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1850')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4931')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4732')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1511')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4315')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1764')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4854')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4754')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1947')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4391')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3892')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2798')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4621')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1735')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2173')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2046')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1201')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4887')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3895')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4349')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4227')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1756')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3506')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4650')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1568')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5226')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1805')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1348')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3250')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4263')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_447')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1202')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2034')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4762')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2541')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2407')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2406')

Warning: Empty candidate sentence detected; setting raw BERTscores to 0.

Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4748')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4157')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1198')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2111')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4368')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1144')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1518')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_254')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4370')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1859')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1650')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4951')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1390')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_639')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2060')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5390')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1322')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4500')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5202')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1192')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_699')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_606')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1262')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2229')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2071')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_443')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4747')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2183')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3342')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4765')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_867')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1194')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1666')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4462')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5071')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2213')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2269')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_754')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4624')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_803')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4272')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2062')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3893')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2601')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4131')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1073')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1489')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4121')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1190')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1634')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2637')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_178')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4735')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4886')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1578')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3906')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1397')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_824')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2187')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1393')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_5194')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4853')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_420')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_4378')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_3375')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_1483')
Attribute error in row ('occiglot-7b-eu5-instruct', 'it_2668')

In [25]:
res_df = pl.from_dict(res)
res_df.describe()

shape: (9, 6)
┌────────────┬──────────────────────────┬───────────┬───────────┬──────────┬──────────┐
│ statistic  ┆ model                    ┆ prompt_id ┆ precision ┆ recall   ┆ f1       │
│ ---        ┆ ---                      ┆ ---       ┆ ---       ┆ ---      ┆ ---      │
│ str        ┆ str                      ┆ str       ┆ f64       ┆ f64      ┆ f64      │
╞════════════╪══════════════════════════╪═══════════╪═══════════╪══════════╪══════════╡
│ count      ┆ 20970                    ┆ 20970     ┆ 20970.0   ┆ 20970.0  ┆ 20970.0  │
│ null_count ┆ 0                        ┆ 0         ┆ 0.0       ┆ 0.0      ┆ 0.0      │
│ mean       ┆ null                     ┆ null      ┆ 0.753305  ┆ 0.753184 ┆ 0.752665 │
│ std        ┆ null                     ┆ null      ┆ 0.099519  ┆ 0.099582 ┆ 0.099083 │
│ min        ┆ gpt-4.1-mini             ┆ it_0      ┆ 0.0       ┆ 0.0      ┆ 0.0      │
│ 25%        ┆ null                     ┆ null      ┆ 0.666406  ┆ 0.666507 ┆ 0.66391  │
│ 50%        ┆ null                     ┆ null      ┆ 0.776832  ┆ 0.777233 ┆ 0.776946 │
│ 75%        ┆ null                     ┆ null      ┆ 0.825858  ┆ 0.825689 ┆ 0.82555  │
│ max        ┆ occiglot-7b-eu5-instruct ┆ it_999    ┆ 1.0       ┆ 1.0      ┆ 1.0      │
└────────────┴──────────────────────────┴───────────┴───────────┴──────────┴──────────┘

In [26]:
skipped

354

In [27]:
res_df.write_csv("bert_score_it.csv")

In [28]:
# French

res = {
    "model": [],
    "prompt_id": [],
    "precision": [],
    "recall": [],
    "f1": []
}

scorer = BERTScorer(lang="fr")
unique_combos = df.filter(pl.col("language")=="fr", pl.col("model")!="Human").select("model", "prompt_id").unique()

skipped = 0

for row in tqdm(unique_combos.iter_rows(), total=unique_combos.height):
    model, prompt_id = row

    sentences = df.filter(
        (pl.col("model") == model), (pl.col("prompt_id") == prompt_id),
    )["argument"].to_list()

    pairs = list(combinations(sentences, 2))
    if not pairs:
        continue

    try:
        cands, refs = zip(*pairs)
        P, R, F1 = scorer.score(list(cands), list(refs))
    
        res["model"].append(model)
        res["prompt_id"].append(prompt_id)
        res["precision"].append(P.mean().item())
        res["recall"].append(R.mean().item())
        res["f1"].append(F1.mean().item())
    except AttributeError:
        print(f"Attribute error in row {row}")
        skipped += 1

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  0%|          | 0/45927 [00:00<?, ?it/s]

In [29]:
skipped

0

In [30]:
res_df = pl.from_dict(res)
res_df.describe()

shape: (9, 6)
┌────────────┬──────────────────────────┬───────────┬───────────┬──────────┬──────────┐
│ statistic  ┆ model                    ┆ prompt_id ┆ precision ┆ recall   ┆ f1       │
│ ---        ┆ ---                      ┆ ---       ┆ ---       ┆ ---      ┆ ---      │
│ str        ┆ str                      ┆ str       ┆ f64       ┆ f64      ┆ f64      │
╞════════════╪══════════════════════════╪═══════════╪═══════════╪══════════╪══════════╡
│ count      ┆ 45800                    ┆ 45800     ┆ 45800.0   ┆ 45800.0  ┆ 45800.0  │
│ null_count ┆ 0                        ┆ 0         ┆ 0.0       ┆ 0.0      ┆ 0.0      │
│ mean       ┆ null                     ┆ null      ┆ 0.767484  ┆ 0.767416 ┆ 0.767013 │
│ std        ┆ null                     ┆ null      ┆ 0.079951  ┆ 0.079833 ┆ 0.079369 │
│ min        ┆ gpt-4.1-mini             ┆ fr_0      ┆ 0.386301  ┆ 0.373209 ┆ 0.389852 │
│ 25%        ┆ null                     ┆ null      ┆ 0.722815  ┆ 0.72326  ┆ 0.72322  │
│ 50%        ┆ null                     ┆ null      ┆ 0.779975  ┆ 0.779787 ┆ 0.778821 │
│ 75%        ┆ null                     ┆ null      ┆ 0.822311  ┆ 0.822063 ┆ 0.821652 │
│ max        ┆ occiglot-7b-eu5-instruct ┆ fr_9999   ┆ 1.0       ┆ 1.0      ┆ 1.0      │
└────────────┴──────────────────────────┴───────────┴───────────┴──────────┴──────────┘

In [31]:
res_df.write_csv("bert_score_fr.csv")